In [1]:
from src.api import get_league_data
from src.config import config
from src.utils import cache_summary
import tqdm

LEAGUE_ID = config.league_id
YEARS = config.years
cookies = config.cookies
headers = config.headers

MAX_PERIODS = 20  # overshoot safe; ESPN just returns no data

In [2]:
print("\n📊 Cache BEFORE population:")
display(cache_summary(YEARS, max_period=MAX_PERIODS, league_id=LEAGUE_ID))

📊 Cache BEFORE population:

     1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19 20
2025  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2024  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ⬜  ✅  ✅  ✅  ✅  ✅  ✗  ✗  ✗
2023  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✗  ✗  ✗
2022  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✗  ✗  ✗
2021  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✗  ✗  ✗
2020  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✗  ✗  ✗  ✗
2019  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✗  ✗  ✗  ✗
2018  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✗  ✗  ✗  ✗
2017  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗
2016  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗
2015  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗

In [3]:
from tqdm import tqdm
import logging

# Make tqdm and logging play nice
class TqdmLoggingHandler(logging.StreamHandler):
    def emit(self, record):
        try:
            msg = self.format(record)
            tqdm.write(msg)  # ensures log lines don't overwrite bars
            self.flush()
        except Exception:
            self.handleError(record)

# Attach handler once
root_logger = logging.getLogger()
if not any(isinstance(h, TqdmLoggingHandler) for h in root_logger.handlers):
    handler = TqdmLoggingHandler()
    handler.setFormatter(logging.Formatter("%(levelname)s: %(message)s"))
    root_logger.addHandler(handler)
    root_logger.setLevel(logging.INFO)

# --- Population loop ---
for year in YEARS:
    for period in tqdm(range(1, MAX_PERIODS + 1), desc=f"Year {year}"):
        data = get_league_data(
            LEAGUE_ID,
            year,
            scoring_period=period,
            cookies=cookies,
            headers=headers,
            use_cache=True,       # respect existing cache
            force_refresh=False,  # don’t blow away existing
        )
        if data is None:
            # Skipped: either future week (retry later) or past-year miss (cached as None)
            continue

Year 2025:  80%|████████  | 16/20 [00:01<00:00,  9.80it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2025, period=16, views=['mMatchup', 'mTeam'])
INFO: Skipping cache for current-year miss (league=1283828, year=2025, period=16, views=['mMatchup', 'mTeam'])

Year 2025:  80%|████████  | 16/20 [00:01<00:00,  9.80it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2025, period=17, views=['mMatchup', 'mTeam'])
INFO: Skipping cache for current-year miss (league=1283828, year=2025, period=17, views=['mMatchup', 'mTeam'])

Year 2025:  80%|████████  | 16/20 [00:01<00:00,  9.80it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2025, period=18, views=['mMatchup', 'mTeam'])
INFO: Skipping cache for current-year miss (league=1283828, year=2025, period=18, views=['mMatchup', 'mTeam'])

Year 2025:  95%|█████████▌| 19/20 [00:02<00:00,  5.90it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2025, period=19, views=['mMatchup', 'mTeam'])
INFO: Skipping cache for current-year miss (league=1283828, year=2025, period=19, views=['mMatchup', 'mTeam'])

Year 2025: 100%|██████████| 20/20 [00:02<00:00,  7.99it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2025, period=20, views=['mMatchup', 'mTeam'])
INFO: Skipping cache for current-year miss (league=1283828, year=2025, period=20, views=['mMatchup', 'mTeam'])

Year 2024:  90%|█████████ | 18/20 [00:01<00:00, 14.29it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2024, period=18, views=['mMatchup', 'mTeam'])

Year 2024:  90%|█████████ | 18/20 [00:01<00:00, 14.29it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2024, period=19, views=['mMatchup', 'mTeam'])

Year 2024: 100%|██████████| 20/20 [00:02<00:00,  9.18it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2024, period=20, views=['mMatchup', 'mTeam'])

Year 2023:  90%|█████████ | 18/20 [00:00<00:00, 42.50it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2023, period=18, views=['mMatchup', 'mTeam'])

Year 2023:  90%|█████████ | 18/20 [00:00<00:00, 42.50it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2023, period=19, views=['mMatchup', 'mTeam'])

Year 2023: 100%|██████████| 20/20 [00:00<00:00, 22.04it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2023, period=20, views=['mMatchup', 'mTeam'])

Year 2022:  90%|█████████ | 18/20 [00:00<00:00, 49.01it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2022, period=18, views=['mMatchup', 'mTeam'])

Year 2022:  90%|█████████ | 18/20 [00:00<00:00, 49.01it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2022, period=19, views=['mMatchup', 'mTeam'])
WARNING: ⚠️ No valid matchups found (league=1283828, year=2022, period=20, views=['mMatchup', 'mTeam'])

Year 2022: 100%|██████████| 20/20 [00:00<00:00, 24.51it/s]
Year 2021:  60%|██████    | 12/20 [00:00<00:00, 115.86it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2021, period=18, views=['mMatchup', 'mTeam'])

Year 2021:  60%|██████    | 12/20 [00:00<00:00, 115.86it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2021, period=19, views=['mMatchup', 'mTeam'])

Year 2021: 100%|██████████| 20/20 [00:00<00:00, 24.36it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2021, period=20, views=['mMatchup', 'mTeam'])

Year 2020:  85%|████████▌ | 17/20 [00:00<00:00, 35.71it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2020, period=17, views=['mMatchup', 'mTeam'])

Year 2020:  85%|████████▌ | 17/20 [00:00<00:00, 35.71it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2020, period=18, views=['mMatchup', 'mTeam'])

Year 2020:  85%|████████▌ | 17/20 [00:01<00:00, 35.71it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2020, period=19, views=['mMatchup', 'mTeam'])

Year 2020: 100%|██████████| 20/20 [00:01<00:00, 15.81it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2020, period=20, views=['mMatchup', 'mTeam'])

Year 2019:  80%|████████  | 16/20 [00:00<00:00, 154.23it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2019, period=17, views=['mMatchup', 'mTeam'])
WARNING: ⚠️ No valid matchups found (league=1283828, year=2019, period=18, views=['mMatchup', 'mTeam'])

Year 2019:  80%|████████  | 16/20 [00:00<00:00, 154.23it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2019, period=19, views=['mMatchup', 'mTeam'])

Year 2019: 100%|██████████| 20/20 [00:01<00:00, 19.35it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2019, period=20, views=['mMatchup', 'mTeam'])

Year 2018:  85%|████████▌ | 17/20 [00:00<00:00, 75.37it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2018, period=17, views=['mMatchup', 'mTeam'])
WARNING: ⚠️ No valid matchups found (league=1283828, year=2018, period=18, views=['mMatchup', 'mTeam'])

Year 2018:  85%|████████▌ | 17/20 [00:00<00:00, 75.37it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2018, period=19, views=['mMatchup', 'mTeam'])

Year 2018: 100%|██████████| 20/20 [00:00<00:00, 23.32it/s]

WARNING: ⚠️ No valid matchups found (league=1283828, year=2018, period=20, views=['mMatchup', 'mTeam'])

Year 2017:   5%|▌         | 1/20 [00:00<00:03,  6.31it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2017, period=1, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2017/segments/0/leagues/1283828?scoringPeriodId=1&SPID=1&matchupPeriodId%3D=1&view=mMatchup&view=mTeam

Year 2017:  10%|█         | 2/20 [00:00<00:02,  6.46it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2017, period=2, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2017/segments/0/leagues/1283828?scoringPeriodId=2&SPID=2&matchupPeriodId%3D=2&view=mMatchup&view=mTeam

Year 2017:  15%|█▌        | 3/20 [00:00<00:02,  5.94it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2017, period=3, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2017/segments/0/leagues/1283828?scoringPeriodId=3&SPID=3&matchupPeriodId%3D=3&view=mMatchup&view=mTeam

Year 2017:  20%|██        | 4/20 [00:00<00:02,  6.21it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2017, period=4, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2017/segments/0/leagues/1283828?scoringPeriodId=4&SPID=4&matchupPeriodId%3D=4&view=mMatchup&view=mTeam

Year 2017:  25%|██▌       | 5/20 [00:00<00:02,  6.43it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2017, period=5, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2017/segments/0/leagues/1283828?scoringPeriodId=5&SPID=5&matchupPeriodId%3D=5&view=mMatchup&view=mTeam

Year 2017:  30%|███       | 6/20 [00:00<00:02,  6.74it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2017, period=6, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2017/segments/0/leagues/1283828?scoringPeriodId=6&SPID=6&matchupPeriodId%3D=6&view=mMatchup&view=mTeam

Year 2017:  35%|███▌      | 7/20 [00:01<00:01,  6.55it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2017, period=7, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2017/segments/0/leagues/1283828?scoringPeriodId=7&SPID=7&matchupPeriodId%3D=7&view=mMatchup&view=mTeam

Year 2017:  40%|████      | 8/20 [00:01<00:01,  6.57it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2017, period=8, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2017/segments/0/leagues/1283828?scoringPeriodId=8&SPID=8&matchupPeriodId%3D=8&view=mMatchup&view=mTeam

Year 2017:  45%|████▌     | 9/20 [00:01<00:01,  6.57it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2017, period=9, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2017/segments/0/leagues/1283828?scoringPeriodId=9&SPID=9&matchupPeriodId%3D=9&view=mMatchup&view=mTeam

Year 2017:  50%|█████     | 10/20 [00:01<00:01,  6.39it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2017, period=10, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2017/segments/0/leagues/1283828?scoringPeriodId=10&SPID=10&matchupPeriodId%3D=10&view=mMatchup&view=mTeam

Year 2017:  55%|█████▌    | 11/20 [00:01<00:01,  6.32it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2017, period=11, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2017/segments/0/leagues/1283828?scoringPeriodId=11&SPID=11&matchupPeriodId%3D=11&view=mMatchup&view=mTeam

Year 2017:  60%|██████    | 12/20 [00:01<00:01,  6.02it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2017, period=12, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2017/segments/0/leagues/1283828?scoringPeriodId=12&SPID=12&matchupPeriodId%3D=12&view=mMatchup&view=mTeam

Year 2017:  65%|██████▌   | 13/20 [00:02<00:01,  6.30it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2017, period=13, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2017/segments/0/leagues/1283828?scoringPeriodId=13&SPID=13&matchupPeriodId%3D=13&view=mMatchup&view=mTeam

Year 2017:  70%|███████   | 14/20 [00:02<00:00,  6.37it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2017, period=14, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2017/segments/0/leagues/1283828?scoringPeriodId=14&SPID=14&matchupPeriodId%3D=14&view=mMatchup&view=mTeam

Year 2017:  75%|███████▌  | 15/20 [00:02<00:00,  6.25it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2017, period=15, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2017/segments/0/leagues/1283828?scoringPeriodId=15&SPID=15&matchupPeriodId%3D=15&view=mMatchup&view=mTeam

Year 2017:  80%|████████  | 16/20 [00:02<00:00,  6.49it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2017, period=16, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2017/segments/0/leagues/1283828?scoringPeriodId=16&SPID=16&matchupPeriodId%3D=16&view=mMatchup&view=mTeam

Year 2017:  85%|████████▌ | 17/20 [00:02<00:00,  6.74it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2017, period=17, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2017/segments/0/leagues/1283828?scoringPeriodId=17&SPID=17&matchupPeriodId%3D=17&view=mMatchup&view=mTeam

Year 2017:  90%|█████████ | 18/20 [00:02<00:00,  6.48it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2017, period=18, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2017/segments/0/leagues/1283828?scoringPeriodId=18&SPID=18&matchupPeriodId%3D=18&view=mMatchup&view=mTeam

Year 2017:  95%|█████████▌| 19/20 [00:02<00:00,  6.42it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2017, period=19, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2017/segments/0/leagues/1283828?scoringPeriodId=19&SPID=19&matchupPeriodId%3D=19&view=mMatchup&view=mTeam

Year 2017: 100%|██████████| 20/20 [00:03<00:00,  6.44it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2017, period=20, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2017/segments/0/leagues/1283828?scoringPeriodId=20&SPID=20&matchupPeriodId%3D=20&view=mMatchup&view=mTeam

Year 2016:   5%|▌         | 1/20 [00:00<00:02,  7.24it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2016, period=1, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2016/segments/0/leagues/1283828?scoringPeriodId=1&SPID=1&matchupPeriodId%3D=1&view=mMatchup&view=mTeam

Year 2016:  15%|█▌        | 3/20 [00:00<00:03,  5.29it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2016, period=2, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2016/segments/0/leagues/1283828?scoringPeriodId=2&SPID=2&matchupPeriodId%3D=2&view=mMatchup&view=mTeam
WARNING: ⚠️ Request failed (league=1283828, year=2016, period=3, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2016/segments/0/leagues/1283828?scoringPeriodId=3&SPID=3&matchupPeriodId%3D=3&view=mMatchup&view=mTeam

Year 2016:  25%|██▌       | 5/20 [00:00<00:02,  6.11it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2016, period=4, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2016/segments/0/leagues/1283828?scoringPeriodId=4&SPID=4&matchupPeriodId%3D=4&view=mMatchup&view=mTeam
WARNING: ⚠️ Request failed (league=1283828, year=2016, period=5, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2016/segments/0/leagues/1283828?scoringPeriodId=5&SPID=5&matchupPeriodId%3D=5&view=mMatchup&view=mTeam

Year 2016:  35%|███▌      | 7/20 [00:01<00:02,  6.30it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2016, period=6, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2016/segments/0/leagues/1283828?scoringPeriodId=6&SPID=6&matchupPeriodId%3D=6&view=mMatchup&view=mTeam
WARNING: ⚠️ Request failed (league=1283828, year=2016, period=7, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2016/segments/0/leagues/1283828?scoringPeriodId=7&SPID=7&matchupPeriodId%3D=7&view=mMatchup&view=mTeam

Year 2016:  45%|████▌     | 9/20 [00:01<00:01,  6.18it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2016, period=8, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2016/segments/0/leagues/1283828?scoringPeriodId=8&SPID=8&matchupPeriodId%3D=8&view=mMatchup&view=mTeam
WARNING: ⚠️ Request failed (league=1283828, year=2016, period=9, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2016/segments/0/leagues/1283828?scoringPeriodId=9&SPID=9&matchupPeriodId%3D=9&view=mMatchup&view=mTeam

Year 2016:  55%|█████▌    | 11/20 [00:01<00:01,  6.07it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2016, period=10, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2016/segments/0/leagues/1283828?scoringPeriodId=10&SPID=10&matchupPeriodId%3D=10&view=mMatchup&view=mTeam
WARNING: ⚠️ Request failed (league=1283828, year=2016, period=11, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2016/segments/0/leagues/1283828?scoringPeriodId=11&SPID=11&matchupPeriodId%3D=11&view=mMatchup&view=mTeam

Year 2016:  65%|██████▌   | 13/20 [00:02<00:01,  5.82it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2016, period=12, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2016/segments/0/leagues/1283828?scoringPeriodId=12&SPID=12&matchupPeriodId%3D=12&view=mMatchup&view=mTeam
WARNING: ⚠️ Request failed (league=1283828, year=2016, period=13, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2016/segments/0/leagues/1283828?scoringPeriodId=13&SPID=13&matchupPeriodId%3D=13&view=mMatchup&view=mTeam

Year 2016:  75%|███████▌  | 15/20 [00:02<00:00,  6.12it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2016, period=14, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2016/segments/0/leagues/1283828?scoringPeriodId=14&SPID=14&matchupPeriodId%3D=14&view=mMatchup&view=mTeam
WARNING: ⚠️ Request failed (league=1283828, year=2016, period=15, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2016/segments/0/leagues/1283828?scoringPeriodId=15&SPID=15&matchupPeriodId%3D=15&view=mMatchup&view=mTeam

Year 2016:  85%|████████▌ | 17/20 [00:02<00:00,  6.50it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2016, period=16, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2016/segments/0/leagues/1283828?scoringPeriodId=16&SPID=16&matchupPeriodId%3D=16&view=mMatchup&view=mTeam
WARNING: ⚠️ Request failed (league=1283828, year=2016, period=17, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2016/segments/0/leagues/1283828?scoringPeriodId=17&SPID=17&matchupPeriodId%3D=17&view=mMatchup&view=mTeam

Year 2016:  90%|█████████ | 18/20 [00:02<00:00,  6.66it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2016, period=18, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2016/segments/0/leagues/1283828?scoringPeriodId=18&SPID=18&matchupPeriodId%3D=18&view=mMatchup&view=mTeam

Year 2016: 100%|██████████| 20/20 [00:03<00:00,  5.99it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2016, period=19, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2016/segments/0/leagues/1283828?scoringPeriodId=19&SPID=19&matchupPeriodId%3D=19&view=mMatchup&view=mTeam
WARNING: ⚠️ Request failed (league=1283828, year=2016, period=20, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2016/segments/0/leagues/1283828?scoringPeriodId=20&SPID=20&matchupPeriodId%3D=20&view=mMatchup&view=mTeam

Year 2015:  10%|█         | 2/20 [00:00<00:02,  7.01it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2015, period=1, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2015/segments/0/leagues/1283828?scoringPeriodId=1&SPID=1&matchupPeriodId%3D=1&view=mMatchup&view=mTeam
WARNING: ⚠️ Request failed (league=1283828, year=2015, period=2, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2015/segments/0/leagues/1283828?scoringPeriodId=2&SPID=2&matchupPeriodId%3D=2&view=mMatchup&view=mTeam

Year 2015:  20%|██        | 4/20 [00:00<00:02,  7.28it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2015, period=3, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2015/segments/0/leagues/1283828?scoringPeriodId=3&SPID=3&matchupPeriodId%3D=3&view=mMatchup&view=mTeam
WARNING: ⚠️ Request failed (league=1283828, year=2015, period=4, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2015/segments/0/leagues/1283828?scoringPeriodId=4&SPID=4&matchupPeriodId%3D=4&view=mMatchup&view=mTeam

Year 2015:  30%|███       | 6/20 [00:00<00:02,  6.84it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2015, period=5, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2015/segments/0/leagues/1283828?scoringPeriodId=5&SPID=5&matchupPeriodId%3D=5&view=mMatchup&view=mTeam
WARNING: ⚠️ Request failed (league=1283828, year=2015, period=6, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2015/segments/0/leagues/1283828?scoringPeriodId=6&SPID=6&matchupPeriodId%3D=6&view=mMatchup&view=mTeam

Year 2015:  40%|████      | 8/20 [00:01<00:01,  6.07it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2015, period=7, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2015/segments/0/leagues/1283828?scoringPeriodId=7&SPID=7&matchupPeriodId%3D=7&view=mMatchup&view=mTeam
WARNING: ⚠️ Request failed (league=1283828, year=2015, period=8, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2015/segments/0/leagues/1283828?scoringPeriodId=8&SPID=8&matchupPeriodId%3D=8&view=mMatchup&view=mTeam

Year 2015:  50%|█████     | 10/20 [00:01<00:01,  6.63it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2015, period=9, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2015/segments/0/leagues/1283828?scoringPeriodId=9&SPID=9&matchupPeriodId%3D=9&view=mMatchup&view=mTeam
WARNING: ⚠️ Request failed (league=1283828, year=2015, period=10, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2015/segments/0/leagues/1283828?scoringPeriodId=10&SPID=10&matchupPeriodId%3D=10&view=mMatchup&view=mTeam

Year 2015:  60%|██████    | 12/20 [00:01<00:01,  6.61it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2015, period=11, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2015/segments/0/leagues/1283828?scoringPeriodId=11&SPID=11&matchupPeriodId%3D=11&view=mMatchup&view=mTeam
WARNING: ⚠️ Request failed (league=1283828, year=2015, period=12, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2015/segments/0/leagues/1283828?scoringPeriodId=12&SPID=12&matchupPeriodId%3D=12&view=mMatchup&view=mTeam

Year 2015:  70%|███████   | 14/20 [00:02<00:00,  6.30it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2015, period=13, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2015/segments/0/leagues/1283828?scoringPeriodId=13&SPID=13&matchupPeriodId%3D=13&view=mMatchup&view=mTeam
WARNING: ⚠️ Request failed (league=1283828, year=2015, period=14, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2015/segments/0/leagues/1283828?scoringPeriodId=14&SPID=14&matchupPeriodId%3D=14&view=mMatchup&view=mTeam

Year 2015:  80%|████████  | 16/20 [00:02<00:00,  6.38it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2015, period=15, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2015/segments/0/leagues/1283828?scoringPeriodId=15&SPID=15&matchupPeriodId%3D=15&view=mMatchup&view=mTeam
WARNING: ⚠️ Request failed (league=1283828, year=2015, period=16, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2015/segments/0/leagues/1283828?scoringPeriodId=16&SPID=16&matchupPeriodId%3D=16&view=mMatchup&view=mTeam

Year 2015:  90%|█████████ | 18/20 [00:02<00:00,  6.54it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2015, period=17, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2015/segments/0/leagues/1283828?scoringPeriodId=17&SPID=17&matchupPeriodId%3D=17&view=mMatchup&view=mTeam
WARNING: ⚠️ Request failed (league=1283828, year=2015, period=18, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2015/segments/0/leagues/1283828?scoringPeriodId=18&SPID=18&matchupPeriodId%3D=18&view=mMatchup&view=mTeam

Year 2015: 100%|██████████| 20/20 [00:03<00:00,  6.51it/s]

WARNING: ⚠️ Request failed (league=1283828, year=2015, period=19, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2015/segments/0/leagues/1283828?scoringPeriodId=19&SPID=19&matchupPeriodId%3D=19&view=mMatchup&view=mTeam
WARNING: ⚠️ Request failed (league=1283828, year=2015, period=20, views=['mMatchup', 'mTeam']): 404 Client Error:  for url: https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl/seasons/2015/segments/0/leagues/1283828?scoringPeriodId=20&SPID=20&matchupPeriodId%3D=20&view=mMatchup&view=mTeam

In [4]:
print("\n📊 Cache AFTER population:")
display(cache_summary(YEARS, max_period=MAX_PERIODS, league_id=LEAGUE_ID))

📊 Cache AFTER population:

     1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19 20
2025  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2024  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✗  ✗  ✗
2023  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✗  ✗  ✗
2022  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✗  ✗  ✗
2021  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✗  ✗  ✗
2020  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✗  ✗  ✗  ✗
2019  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✗  ✗  ✗  ✗
2018  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✅  ✗  ✗  ✗  ✗
2017  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗
2016  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗
2015  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗  ✗

In [4]:
from src.data import load_cache_entry
import json

def inspect_matchups(league_id, year, period, views=("mMatchup", "mTeam")):
    """
    Inspect cached matchups for a given year + scoring period.
    """
    data = load_cache_entry(league_id, year, period, list(views))
    if data is None:
        print(f"❌ No cache entry for {year} period {period}")
        return

    # Filter to actual matchups for this scoring period
    matches = [
        row for row in data.get("schedule", [])
        if row.get("matchupPeriodId") == period
    ]

    print(f"✅ Cache entry loaded for {year} period {period}")
    print("Teams length:", len(data.get("teams", [])))
    print(f"Matchups found for period {period}: {len(matches)}")

    if matches:
        for m in matches:
            home = m["home"]["teamId"]
            away = m["away"]["teamId"]
            home_points = m["home"].get("totalPoints", 0)
            away_points = m["away"].get("totalPoints", 0)
            print(f"Week {period}: Team {home} ({home_points}) vs Team {away} ({away_points})")
    else:
        print("⚠️ No matchups in schedule for this period")

# ---- Example usage ----
inspect_matchups(LEAGUE_ID, 2023, 10)

✅ Cache entry loaded for 2023 period 10
Teams length: 12
Matchups found for period 10: 6
Week 10: Team 8 (111.0) vs Team 1 (150.1)
Week 10: Team 2 (117.2) vs Team 4 (129.0)
Week 10: Team 5 (88.7) vs Team 6 (103.4)
Week 10: Team 11 (91.1) vs Team 12 (116.8)
Week 10: Team 7 (136.5) vs Team 9 (119.4)
Week 10: Team 10 (97.8) vs Team 3 (75.6)